-- MySQL Script generated by MySQL Workbench
-- Wed Jan 14 14:41:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web4heroes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web4heroes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web4heroes` DEFAULT CHARACTER SET utf8 ;
USE `web4heroes` ;

-- -----------------------------------------------------
-- Table `web4heroes`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`adresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street&numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `street&numero_UNIQUE` (`street&numero` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `pwd` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `gender` ENUM('Male', 'Femelle', 'other') NULL DEFAULT 'Other',
  `birthdate` DATE NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `street_number` INT NOT NULL,
  `complement_number` VARCHAR(45) NULL,
  `street` VARCHAR(100) NOT NULL,
  `zipcode` INT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `role` JSON NULL COMMENT '[‘ROLE_USER’, ‘ROLE_ADMIN’, [‘test_donnee’]]\n\n$user[0] = ‘ROLE_USER’;\nIf ($userr',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`villain_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`villain_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(55) NOT NULL,
  `name` VARCHAR(45) NULL,
  `specialty` ENUM('Inconnu', 'Vol', 'Cambriolage', 'Meurtre', 'Attentat', 'Prise d''otages') NOT NULL,
  `sector` ENUM('Inconnu', 'Hell''s Kitchen', 'Madripoor', 'Latveria', 'Sokovia', 'Genosha') NOT NULL,
  `description` LONGTEXT NOT NULL,
  `photo_path` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC) ,
  UNIQUE INDEX `photo_path_UNIQUE` (`photo_path` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`hero_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`hero_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(55) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `photo_path` VARCHAR(100) NOT NULL,
  `is_active` TINYINT NULL DEFAULT 1,
  `users_id` INT NOT NULL,
  `specialty` ENUM('Inconnu', 'Vol', 'Cambriolage', 'Meurtre', 'Attentat', 'Prise d''otages') NOT NULL,
  `sector` ENUM('Inconnu', 'Hell''s Kitchen', 'Madripoor', 'Latveria', 'Sokovia', 'Genosha') NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC) ,
  INDEX `fk_hero_profile_users1_idx` (`users_id` ASC) ,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) ,
  CONSTRAINT `fk_hero_profile_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `web4heroes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`adresses_incidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`adresses_incidents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `complement_numero` VARCHAR(45) NULL,
  `street` VARCHAR(100) NOT NULL,
  `zipcode` INT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`incidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`incidents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `priority` ENUM('Low', 'Mid', 'High') NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT 'ENUM ?',
  `users_id` INT NOT NULL,
  `villain_profile_id` INT NULL,
  `status` ENUM('En attanete', 'En cours', 'Terminé') NOT NULL,
  `adresses_incidents_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `villain_profile_id`, `adresses_incidents_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_incidents_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_incidents_villain_profile1_idx` (`villain_profile_id` ASC) ,
  INDEX `fk_incidents_adresses_incidents1_idx` (`adresses_incidents_id` ASC) ,
  CONSTRAINT `fk_incidents_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `web4heroes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidents_villain_profile1`
    FOREIGN KEY (`villain_profile_id`)
    REFERENCES `web4heroes`.`villain_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidents_adresses_incidents1`
    FOREIGN KEY (`adresses_incidents_id`)
    REFERENCES `web4heroes`.`adresses_incidents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `imdb_path` VARCHAR(255) NOT NULL,
  `poster_path` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`newsletter_subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`newsletter_subscribers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscribed_at` DATETIME NULL,
  `email` VARCHAR(100) NOT NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_newsletter_subscribers_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_newsletter_subscribers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `web4heroes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operationcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`intervention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`intervention` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incidents_id` INT NOT NULL,
  `hero_profile_id` INT NULL,
  `status` ENUM('En attente', 'En Cours', 'résolu') NOT NULL,
  `date_open` DATETIME NULL,
  `date_close` DATETIME NULL,
  PRIMARY KEY (`id`, `incidents_id`, `hero_profile_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_intervention_incidents1_idx` (`incidents_id` ASC) ,
  INDEX `fk_intervention_hero_profile1_idx` (`hero_profile_id` ASC) ,
  UNIQUE INDEX `incidents_id_UNIQUE` (`incidents_id` ASC) ,
  CONSTRAINT `fk_intervention_incidents1`
    FOREIGN KEY (`incidents_id`)
    REFERENCES `web4heroes`.`incidents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intervention_hero_profile1`
    FOREIGN KEY (`hero_profile_id`)
    REFERENCES `web4heroes`.`hero_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web4heroes`.`hero_profile_has_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web4heroes`.`hero_profile_has_movies` (
  `hero_profile_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`hero_profile_id`, `movies_id`),
  INDEX `fk_hero_profile_has_movies_movies1_idx` (`movies_id` ASC) ,
  INDEX `fk_hero_profile_has_movies_hero_profile1_idx` (`hero_profile_id` ASC) ,
  CONSTRAINT `fk_hero_profile_has_movies_hero_profile1`
    FOREIGN KEY (`hero_profile_id`)
    REFERENCES `web4heroes`.`hero_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hero_profile_has_movies_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `web4heroes`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
